### ISSUE TITLE
setup CI

### ISSUE THREAD

**Issue by SwikritiT** [JankariTech/expected-failures-updater#11]
seems like we have some tests https://github.com/JankariTech/expected-failures-updater/tree/main/tests 
but they aren't currently running in CI we can setup a `github` actions workflow to run this test 

The tests are using `bats` https://github.com/bats-core/bats-core 

we need to figure out a way to run the test and setup a ci to run it
https://github.com/JankariTech/expected-failures-updater/blob/main/tests/test_scan_command.bats

## TODO
- [x] setup GitHub actions workflow
- [x] run tests
- [x] add a lint step to check the go lint 
- [x] update the README on how to run the tests locally

**Comment by amrita-shrestha** [comment]
how about adding tests for all possible commands like inspect, shift,cache-and

**Comment by phil-davis** [comment]
IMO this all finished in PR #12
